name: Release

on:
  workflow_dispatch: {}

jobs:
  release:
    permissions:
      contents: write
      packages: write
    uses: adamhl8/configs/.github/workflows/release.yml@main
    with:
      docker-image: guild-sim
    secrets: inherit

  publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Publish to homelab
        env:
          WATCHTOWER_API_TOKEN: ${{ secrets.WATCHTOWER_API_TOKEN }}
        run: |
          curl \
            --fail \
            -X POST \
            -H "Authorization: Bearer $WATCHTOWER_API_TOKEN" \
            https://watchtower.guild-sim.adamhl.dev/v1/update
